### ISSUE TITLE
Problem with fulfillment

### ISSUE THREAD

**Issue by thomasgcompany** [MishUshakov/dialogflow-web#21]
Hi Mish,

I get the following error in my fulfillment.
Any clue what's going on?

```
TypeError: Cannot read property 'source' of undefined
    at V2Agent.processRequest_ (/user_code/node_modules/dialogflow-fulfillment/src/v2-agent.js:108:86)
    at new WebhookClient (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:201:17)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:17:19)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:37:41)
    at /var/tmp/worker/worker.js:686:7
    at /var/tmp/worker/worker.js:670:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Regards,

Thomas

**Comment by MishUshakov** [comment]
Make sure your fulfilment is properly connected via Dialogflow and the code is fine, I tested it with my fulfilment, got no error
Also note, that the client libraries sometimes have no connection to server, because of Google making updates!

**Comment by thomasgcompany** [comment]
@MishUshakov Still getting errors.
Im using Dialog fulfilment inline editor.

Errors:
`TypeError: Cannot read property 'source' of undefined
    at V2Agent.processRequest_ (/user_code/node_modules/dialogflow-fulfillment/src/v2-agent.js:108:86)
    at new WebhookClient (/user_code/node_modules/dialogflow-fulfillment/src/dialogflow-fulfillment.js:201:17)
    at exports.dialogflowFirebaseFulfillment.functions.https.onRequest (/user_code/index.js:13:19)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:37:41)
    at /var/tmp/worker/worker.js:686:7
    at /var/tmp/worker/worker.js:670:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

My fulfilment code:
```javascript
const functions = require('firebase-functions');
const firebaseAdmin = require('firebase-admin');
const {WebhookClient} = require('dialogflow-fulfillment');
const {Card, Suggestion} = require('dialogflow-fulfillment');

process.env.DEBUG = 'dialogflow:debug'; // enables lib debugging statements

exports.dialogflowFirebaseFulfillment = functions.https.onRequest((request, response) => {
    const agent = new WebhookClient({ request, response });
    const reqBody = request.body;
    console.log('Dialogflow Request headers: ' + JSON.stringify(request.headers));
    console.log('Dialogflow Request body: ' + JSON.stringify(reqBody));

    function testFunctionHandler(agent){
        agent.add(new Card({
                title: `Je nieuwe wachtwoord is:`,
                imageUrl: 'https://developers.google.com/actions/images/badges/XPM_BADGING_GoogleAssistant_VER.png',
                buttonText: 'Klik hier om in te loggen',
                buttonUrl: 'google.com  '
              })
            );
    }
    
    let intentMap = new Map();
    intentMap.set('Test intent', testFunctionHandler);

    agent.handleRequest(intentMap);

});
```

And screenshots:

<img width="1154" alt="screen shot 2018-04-27 at 08 37 21" src="https://user-images.githubusercontent.com/20685322/39348212-720a8d26-49f6-11e8-83ef-efe9cfbbe45f.png">
<img width="609" alt="screen shot 2018-04-27 at 08 37 37" src="https://user-images.githubusercontent.com/20685322/39348218-7907ae38-49f6-11e8-98a2-cd6119b9fc69.png">

**Comment by kimneu** [comment]
@thomasgcompany does your service-worker work/load?
because mine doesn't.

console showing me this:
`The script has an unsupported MIME type ('text/x-js').`
`Failed to load resource: net::ERR_INSECURE_RESPONSE`
`(index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/x-js').`

so the fulfillment is not working on my own domain,
but it is working on facebook's messenger and dialogflow test dialog in the console.

**Comment by thomasgcompany** [comment]
@kimneu  im not really sure what you mean but this is the output of my console.
Do you think there is a problem in my code? 
Could you give me an example fulfilment code that does work?

<img width="690" alt="screen shot 2018-04-27 at 20 25 08" src="https://user-images.githubusercontent.com/20685322/39378587-249cc712-4a59-11e8-8460-4205bd99b28e.png">

**Comment by thomasgcompany** [comment]
Hi Guys,

I tried with the example fulfillment but no luck:
It gives me errors on:   
`const agent = new WebhookClient({ request, response });
`
https://github.com/dialogflow/dialogflow-fulfillment-nodejs/blob/master/samples/quick-start/functions/index.js

I would be very happy if you could help me figure out whats the problem.

Regards,

Thomas

**Comment by kimneu** [comment]
hey @thomasgcompany 

so basically I have the same problem, I think.
my thought was, that it could have something todo with the service-worker.js, since I have troubles loading this file on my live version. but in the end, why should the webhook / fulfillment be affected by the service-worker. 🤷‍♂️

<img width="415" alt="bildschirmfoto 2018-04-28 um 12 25 17" src="https://user-images.githubusercontent.com/16124019/39395564-44256166-4ae0-11e8-80b4-d6b924f1e670.png">
<img width="362" alt="bildschirmfoto 2018-04-28 um 12 25 38" src="https://user-images.githubusercontent.com/16124019/39395565-444559ee-4ae0-11e8-99c2-573f83d4a411.png">

![img_92697043fb28-1](https://user-images.githubusercontent.com/16124019/39395570-4b93675e-4ae0-11e8-8a0c-3e06f2bdb2e5.jpeg)

**Comment by thomasgcompany** [comment]
@kimneu Yes you have the same problem!

**Comment by MishUshakov** [comment]
@thomasgcompany  @kimneu honestly i doesnt know what you are talking about, do you use V2 API?

**Comment by diazabdulm** [comment]
Any examples/guides on how to implement fulfillment?

**Comment by thomas-vl** [comment]
Yes! I just switched from V2 to V1 and then I don't get errors but it does not show a card.
Do you require API V2 or V1?
If you require V1 can I help upgrade the code to use the V2 API?

**Comment by thomasgcompany** [comment]
@MishUshakov  
Sorry thomas-vl is my private account...

I think its not wise to try and rebuild the entire ApiAiClient library.
I can just rewrite everything that uses the Library to use the reset api.

Do you want to create a different branch for the V2 development?

Regards,

Thomas

**Comment by MishUshakov** [comment]
@thomasgcompany 
Yep, just fork the lib and create your REST client(I recommend using fetch API) if you want, shouln't be hard I think :D

Thank you for your investigation ❤️

**Comment by thomasgcompany** [comment]
@MishUshakov,

I think we have to stick to v1 for a while unless you have some brilliant idea how to get oAuth 2.0 with service account done in javascript.
See the guide:
https://dialogflow.com/docs/reference/v2-auth-setup

Regards,

Thomas

**Comment by MishUshakov** [comment]
@thomasgcompany check this https://developers.google.com/identity/protocols/OAuth2UserAgent

**Comment by thomasgcompany** [comment]
@MishUshakov Yes, that does only do Login oAuth to authenticate a user or oAuth1.0 with a token.
We need this one https://developers.google.com/identity/protocols/OAuth2ServiceAccount

There are a couple of ways to move forward:

Build a serverside controller to run all the API requests and host the complete thing on App Engine
Build a Cloud Function to handle authentication, send the Token to the the client and make the API requests Client side.

**Comment by MishUshakov** [comment]
@thomasgcompany yeah, actually I doesn't want to build a whole OAuth 2.0 server for just authentication, in many ways it can be insecure and it also will cost addition money to serve. I will try to find other ways to connect V2 Projects into web apps, because for me as developer it is a frustrating experience if the standard javascript library from dialogflow, which I use can not handle V2.

I will have to wait for a stable dialogflow JS-Client release, which supports the service accounts and V2 etc. 

Thank you for your support on this question 👍

**Comment by kimneu** [comment]
@thomasgcompany sorry to chip in so late, but did you get the fulfillment working on the web?
i still have this issue, using V1. can't get my head around why..
