### ISSUE TITLE
Does not work on IE

### ISSUE THREAD

**Issue by ramonck** [MishUshakov/dialogflow-web#3]
Sintax error on build.js line 1 Character 707.

**Comment by MishUshakov** [comment]
Hey, @ramonck thank you for your feedback! I tried loading the project using IE 10 it worked just fine, which version are you using?

**Comment by ramonck** [comment]
IE 11

**Comment by MishUshakov** [comment]
Ok, i will look on the situation there and report, stay tuned for future releases!

**Comment by MishUshakov** [comment]
Hey @ramonck try to set this param in your webpack.config.js to true, seems to fix the issue. This is the line 70 ie8: false, which drops support for internet explorer, if you still have issues remove the uglify plugin from your webpack config. Have fun with the project! Case issue remains, keep me updated in here, I will close the issue for now, because, it fixed the problem for me.

<img width="171" alt="screen shot 2018-02-02 at 21 32 46" src="https://user-images.githubusercontent.com/10400064/35753590-a83edcbc-0860-11e8-8bcb-7cf84d472826.png">
