### ISSUE TITLE
 Cross domain error occurred

### ISSUE THREAD

**Issue by yambal** [MishUshakov/dialogflow-web#61]
Cross domain error occurred

// error -------
Failed to load https://api.api.ai/v1/query?v=20150910: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mishushakov.github.io' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by konato** [comment]
Have the same, what able to correct it temporary by editing the  file APiAiConstants.js of package api-ai-javascript 

By using this temporary solution : 
 ApiAiConstants.DEFAULT_BASE_URL = "https://cors-anywhere.herokuapp.com/https://api.api.ai/v1/";

I did it on the following finding : 
 https://stackoverflow.com/questions/52789961/how-to-use-cors-in-javascript-to-get-response-from-dialogflow-api-ai

and
 
 https://github.com/dialogflow/dialogflow-javascript-client/issues/102

**Comment by MishUshakov** [comment]
That's what happens if your project rely on third-party APIs 😄
Sorry for the inconvenience, clearly not my mistake here. They finally need to rewrite the api.ai client for javascript, or we won't see any future updates for this project.

Or maybe @google or/and @dialogflow would hire me to let me refactor their own widget and build some more useful things for web developers (I know, they don't have time to do that, but I actually do) ❤️

**Comment by yambal** [comment]
I am Japanese and please allow me to translate machinery.

In my recognition, it did not occur until several days ago.

I wonder if the policy of API side recently changed

How to avoid cross domains on a relay server is working well. But it is not smart and the response is slow.

Thanks for the idea

**Comment by daniel-ferraz** [comment]
I'm having this same problem, could you help me?
